### ISSUE TITLE
RuntimeError: Paramedir execution failed

### ISSUE THREAD

**Issue by raymerta** [numericalalgorithmsgroup/pypop#2]
Hi, I am trying to rerun the Jupyter Notebook sample in our cluster and got this error: 
```
RuntimeError: Paramedir execution failed:
/tmp/tmp8abkgbf6/serial_useful_computation.cfg: Some of the events specified in the filter doesn't appear in the trace. File creation aborted.
```
As far as I checked ` os.path.exists(outfile)` returns False and returncode is 0. 

Is it related to the cluster setting for creating temporary directory? and is there any suggestion for this problem?

**Comment by ptooley** [comment]
So this is actually due to an issue with paramedir (bsc-performance-tools/paraver-kernel#5) that has been fixed, where it fails if it cannot find all event types in the filter.

If you are able to install a new version of paraver-kernel (from the devel branch), this will resolve the issue.  If this is not feasible I can try to produce a workaround in the pypop code, but this may take me a few days.

**Comment by ptooley** [comment]
I have now implemented a workaround for this.  Please try again with the latest version and let me know if it is not fixed.

**Comment by raymerta** [comment]
Thank you! I will try it, was trying to update the latest Paraver kernel too in the cluster but it takes more time
